### ISSUE TITLE
what's the meaning of some varibles?

### ISSUE THREAD

**Issue by xylcbd** [ritheshkumar95/im2latex-tensorflow#10]
such as H/W in  https://github.com/ritheshkumar95/im2latex-tensorflow/blob/master/attention.py#L20
H = 20
W = 50
and 160 in https://github.com/ritheshkumar95/im2latex-tensorflow/blob/master/attention.py#L86

What's the meaning of these magic number? the hard code ?

And, I'm confused about the different buckets' size, how it works ?

thank you very much.

**Comment by ritheshkumar95** [comment]
H and W are maximum height and width of pooled representations. 
Look at page 6 footnote for the various bucket sizes (https://arxiv.org/pdf/1609.04938.pdf)
160 is the maximum sequence length that was used during preparation of the im2latex-100k dataset (maximum 160 tokens per image)

**Comment by xylcbd** [comment]
got it. thanks!
