### ISSUE TITLE
Predict issue

### ISSUE THREAD

**Issue by RobinXL** [ritheshkumar95/im2latex-tensorflow#2]
Hi Rithesh,

I see you have included Predict function in the attention.py script, but I didnt see you use it anywhere. Can you indicate how to use it so I can predict my training result?
Thanks a lot

Robin

**Comment by ritheshkumar95** [comment]
Hi Robin, 

So the reason I dont use it anywhere particularly is that I generally train models on a detachable (screen) terminal with my script running in ipython. I generally just call my predict() function with no particular arguments once the training process gets over.

The predict function should work by default if you have all the data prepared as I have instructed. Let me know if you have any issues. 

PS: Follow all my preprocessing instructions, (each and every line). Predict function requires files like test_buckets.npy and val_buckets.npy (which are basically images bucketed based on their size). 

Predict function just randomly samples a mini-batch from those buckets and makes a free-run prediction using *just* the images.

**Comment by RobinXL** [comment]
Hi Rithesh,

Thanks for clarifying! Since my computer is not so powerful and I dont want to spend too much time waiting. So I just picked like 200 pics to train and test. 

I also wonder if this project is suitable for training handwriting dataset. What's your opinion? 

Robin

**Comment by ritheshkumar95** [comment]
Hi Robin, 

This architecture would certainly work well, for all problems related to OCR (In a way, im2latex itself is a type of OCR task). Handwriting is a harder version of OCR owing to the sheer variance in writing styles. But I must say it should work decently well atleast. 

PS: Considering this architecture, it would be best to preprocess the handwriting data in a similar way, in the sense that you'd have to restrict it to a few bucket sizes not exceed by far in length. The bucket sizes (of images) used in this paper are:  (120,50), (160,40), (200,40),(200,50), (240,40), (240,50), (280,40), (280,50), (320,40),(320,50), (360,40), (360,50), (360,60), (360, 100), (400,50),(400,160), (500,100).

Hope this helps! Good luck!

Best,
Rithesh

**Comment by RobinXL** [comment]
Hi Rithesh,
Thanks for being patient with. I have run a few test and the perplexity is pretty low. However, when I ipython to call the predict function as you mentioned, the predict error pops up:

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value conv3_1//beta
	 [[Node: conv3_1//beta/read = Identity[T=DT_FLOAT, _class=["loc:@conv3_1//beta"], _device="/job:localhost/replica:0/task:0/gpu:0"](conv3_1//beta)]]
	 [[Node: scan_1/while/Identity/_964 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_249_scan_1/while/Identity", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](^_cloopscan_1/while/BiRNN/BW/BW/Assert/Assert/data_2/_949)]]

Do you have any idea about this error?

**Comment by ritheshkumar95** [comment]
Hey Robin,

I fixed this issue (seemed to be pretty new when I ran on my laptop as well). Check the latest commit.

Also, I added a link to my best weight files (from the latest checkpoint). Good luck!

Best,
Rithesh

**Comment by RobinXL** [comment]
Hey Rithesh,
Thank you for fixing the issue :)
