### ISSUE TITLE
variables

### ISSUE THREAD

**Issue by vishalcool1401** [ritheshkumar95/im2latex-tensorflow#7]
could you please tell me the use of these variables in your program.?
EMB_DIM = 80
ENC_DIM = 256
DEC_DIM = ENC_DIM*2

**Comment by ritheshkumar95** [comment]
EMB_DIM -> Dimensionality of the embedding vectors for latex tokens
ENC_DIM -> Dimensionality of the hidden units for the bidirectional encoding of feature grid from the CNN
DEC_DIM -> Dimensionality of the hidden units for the Decoder
