### ISSUE TITLE
Unclear how im2latex_test.lst and others were generated

### ISSUE THREAD

**Issue by mitar** [ritheshkumar95/im2latex-tensorflow#8]
It is unclear how were those lists generated/chosen.

**Comment by ritheshkumar95** [comment]
In this specific work, im2latex_train/test/val.lst were not created / generated, they were just downloaded from the original dataset (https://zenodo.org/record/56198#.WNJclnV94jA)

**Comment by mitar** [comment]
Thanks. Will open an issue in https://github.com/Miffyli/im2latex-dataset.
