### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by vishalcool1401** [ritheshkumar95/im2latex-tensorflow#9]
Whenever i am trying to run your code, i am getting an error in tflib folder in ops.py 

AttributeError: module "tensorflow.python.ops.nn" has no attribute 'rnn_cell'

**Comment by ritheshkumar95** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/ops/rnn_cell.py

Many changes have been made in the new tensorflow version.
My code was for tensorflow 0.12.0-rc0
